import Link from "next/link";
import { redirect } from "next/navigation";
import { getServerSession } from "next-auth";
import { Role } from "@prisma/client";
import { authOptions } from "@/lib/authOptions";
import { db } from "@/lib/db";

function money(v: unknown,c:string){const n=Number(v||0);try{return new Intl.NumberFormat("en-GB",{style:"currency",currency:c}).format(n)}catch{return `${c} ${n.toFixed(2)}`}}
function label(v:string){return v.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,(x)=>x.toUpperCase())}
export default async function SalesDocumentsPage(){const session=await getServerSession(authOptions);if(!session?.user||session.user.role!==Role.ADMIN)redirect("/admin-login");const docs=await db.salesDocument.findMany({orderBy:{createdAt:"desc"},include:{booking:{select:{bookingReference:true}},_count:{select:{items:true}}}});return <div className="mx-auto max-w-[1500px] space-y-6 p-4 sm:p-6 lg:p-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#8B0000]">Finance</p><h1 className="mt-1 text-3xl font-bold text-[#001F3F]">Sales Documents</h1><p className="mt-2 text-sm text-slate-500">Proformas, invoices and credit notes with PDF and email history.</p></div><div className="flex gap-2"><Link href="/admin/finance" className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold">Finance Center</Link><Link href="/admin/finance/sales-documents/create" className="rounded-xl bg-[#8B0000] px-4 py-2.5 text-sm font-semibold text-white">+ New Document</Link></div></div><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Number</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Recipient</th><th className="px-4 py-3">Booking</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Total</th><th className="px-4 py-3"></th></tr></thead><tbody className="divide-y divide-slate-100">{docs.map(d=><tr key={d.id}><td className="px-4 py-3 font-semibold text-[#001F3F]">{d.documentNumber||"Draft"}</td><td className="px-4 py-3">{label(d.type)}</td><td className="px-4 py-3"><div className="font-medium">{d.recipientCompany||d.recipientName}</div><div className="text-xs text-slate-500">{d.recipientEmail||"-"}</div></td><td className="px-4 py-3">{d.booking?.bookingReference||d.bookingReferenceSnapshot||"-"}</td><td className="px-4 py-3"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold">{label(d.status)}</span></td><td className="px-4 py-3 text-right font-semibold">{money(d.totalAmount,d.currency)}</td><td className="px-4 py-3 text-right"><Link href={`/admin/finance/sales-documents/${d.id}`} className="font-semibold text-[#8B0000]">Open →</Link></td></tr>)}{docs.length===0&&<tr><td colSpan={7} className="px-4 py-12 text-center text-slate-500">No sales documents yet.</td></tr>}</tbody></table></div></div></div>}
